// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hsugdbkauxbjuogzmukp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhzdWdkYmthdXhianVvZ3ptdWtwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2ODk1NDUsImV4cCI6MjA2NTI2NTU0NX0.zt8k79ttdiKeEk7HOY7dd0RK_5-D3JbMrSSXZjWamuI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);